package openapi

import "time"

// TestExternalTagged and TestExternalPlain both use the cached external type
// time.Time; the tagged one carries an openapi tag enhancement. They exist to
// verify that inlining a cached schema copies it (tag enhancements on one usage
// must not leak to others or to the shared cache).
type TestExternalTagged struct {
	At time.Time `json:"at" openapi:"title=CreatedAt"`
}

type TestExternalPlain struct {
	At time.Time `json:"at"`
}

// TestSimple is a helper struct used by openapi tests to verify schema generation.
type TestSimple struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

// TestPageInfo carries pagination metadata for TestPaginatedResponse.
type TestPageInfo struct {
	CurrentPage int `json:"currentPage"`
	TotalPages  int `json:"totalPages"`
}

// TestBusinessObject is a concrete payload used to instantiate generics.
type TestBusinessObject struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

// TestPaginatedResponse is a generic envelope: a page of T plus page metadata.
type TestPaginatedResponse[T any] struct {
	Data []T          `json:"data"`
	Page TestPageInfo `json:"page"`
}

// TestGenericPair exercises multiple type parameters and a pointer parameter.
type TestGenericPair[K comparable, V any] struct {
	Key   K  `json:"key"`
	Value *V `json:"value,omitempty"`
}

// TestGenericFieldHolder exercises a struct field whose own type is a generic
// instantiation (the *ast.IndexExpr arm in convertFieldType), as opposed to a
// top-level instantiation requested directly.
type TestGenericFieldHolder struct {
	Envelope TestPaginatedResponse[TestBusinessObject] `json:"envelope"`
}

// TestWithPointer exercises pointer field handling in schema generation.
type TestWithPointer struct {
	Name *string `json:"name,omitempty"`
}

// TestWithArray exercises array field handling in schema generation.
type TestWithArray struct {
	Tags []string `json:"tags"`
}

// TestNested verifies nested struct references across generated schemas.
type TestNested struct {
	Simple TestSimple `json:"simple"`
}

// TestRefSiblings exercises OpenAPI 3.1 sibling keywords on $ref fields:
// a direct ref, a nullable ref, and an untagged ref (leak guard).
type TestRefSiblings struct {
	Decorated TestSimple  `json:"decorated" openapi:"description=the decorated one,deprecated=true,maxLength=50"`
	Nullable  *TestSimple `json:"nullable"  openapi:"description=the nullable one"`
	PlainRef  TestSimple  `json:"plainRef"`
}

// testHelperOther is an auxiliary struct referenced by TestWithQualified.
type testHelperOther struct {
	Foo int `json:"foo"`
}

// TestWithQualified ensures qualified type names are generated for nested structs.
type TestWithQualified struct {
	Other testHelperOther `json:"other"`
}

// TagExample exercises enhanced tag handling when generating schemas.
type TagExample struct {
	ID    string  `json:"id"              openapi:"format=uuid,deprecated=true,default=00000000-0000-0000-0000-000000000000"`
	Alias string  `json:"alias,omitempty" openapi:"pattern=^a.*$,minLength=2,maxLength=5"`
	Email string  `json:"email"                                                                                              validate:"email"`
	Owner string  `json:"owner,omitempty"                                                                                                     binding:"uuid"`
	Count int     `json:"count"           openapi:"description=number of items,default=7,example=42"`
	Rate  float64 `json:"rate"            openapi:"default=1.5"`
	Code  string  `json:"code"            openapi:"pattern=^a{2,5}$,minLength=2"`
}

// MyEnum is a test enum representing string-based constants.
type MyEnum string

const (
	MyEnumA MyEnum = "A"
	MyEnumB MyEnum = "B"
)

// TestWithEnumField verifies that enum fields in structs are properly referenced
type TestWithEnumField struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Status MyEnum `json:"status"`
}

// TestCompliance31 verifies OpenAPI 3.1 specific schema features.
type TestCompliance31 struct {
	Count int     `json:"count" openapi:"exclusiveMin=0,exclusiveMax=100"`
	Rate  float64 `json:"rate"  openapi:"exclusiveMin=0.5"`
}

// TestAliasMap is a type alias for a map.
type TestAliasMap map[string]int

// TestAliasSlice is a type alias for a slice.
type TestAliasSlice []TestSimple

// DiscountType represents discount type values generated by sqlc.
type DiscountType string

const (
	DiscountTypePercentage DiscountType = "percentage"
	DiscountTypeFixed      DiscountType = "fixed"
)

// CouponScope represents scope values for coupons.
type CouponScope string

const (
	CouponScopeGlobal  CouponScope = "global"
	CouponScopePrivate CouponScope = "private"
)

// Coupon is a simplified sqlc-generated struct used by tests.
type Coupon struct {
	ID    int          `json:"id"`
	Type  DiscountType `json:"type"`
	Scope CouponScope  `json:"scope"`
}

// CreatedOrder is a @Success response fixture used to verify that a success
// response type is resolved and registered into components.schemas.
type CreatedOrder struct {
	ID    string `json:"id"`
	Total int    `json:"total"`
}

// OrderProblem is a @Failure response fixture used to verify that a failure
// response type is resolved and registered into components.schemas, the same
// way as a success type.
type OrderProblem struct {
	Message string `json:"message"`
	Code    int    `json:"code"`
}
