package openapi

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log/slog"
	"path/filepath"
	"strings"

	"github.com/kbertalan/chi-openapi/serde"
)

// Annotation represents parsed annotations
type Annotation struct {
	Summary     string
	Description string
	Tags        []string
	Accept      []string
	Security    []SecurityReq     `tag:"Security"`
	See         *ExternalDoc      `tag:"See"`
	Parameters  []ParamAnnotation `tag:"Param"`
	Success     *SuccessResponse  `tag:"Success"`
	Failures    []ErrorResponse   `tag:"Failure"`
}

// ExternalDoc is the @See directive: a link to external documentation, with an
// optional human-readable description. It maps to Operation.ExternalDocs.
type ExternalDoc struct {
	URL         string
	Description string
}

// SecurityReq is one @Security directive: a security scheme name and optional
// OAuth2 scopes. Each directive becomes one entry in Operation.Security (the
// entries are OR-combined per the OpenAPI security model).
type SecurityReq struct {
	Scheme string
	Scopes []string
}

type SuccessResponse struct {
	StatusCode  int
	DataType    string
	Description string
	Produce     []string
}

type ParamAnnotation struct {
	Name        string
	In          string
	Type        string
	Required    bool
	Description string
}

type ErrorResponse struct {
	StatusCode  int
	Type        string
	Description string
	Produce     []string
}

// ParseAnnotations reads the AST for the provided Go source file (or the
// project's TypeIndex cache) and extracts comment block annotations for the
// function named by `functionName`.
//
// Behavior notes:
//   - Returns nil, nil if no suitable file or comments are found (not an error).
//   - Uses a local AST file cache to avoid repeated parsing of the same file.
//   - Accepts fully-qualified function names (e.g. "menu.handler.List") and
//     extracts the simple function name before matching the AST node.

func ParseAnnotations(filePath, functionName string) (*Annotation, error) {
	normalizedFilePath := filepath.ToSlash(filePath)
	if strings.Contains(normalizedFilePath, "\\") {
		normalizedFilePath = strings.ReplaceAll(normalizedFilePath, "\\", "/")
	}
	if filePath == "" || filePath == "<autogenerated>" ||
		strings.Contains(normalizedFilePath, "/go/pkg/mod/") ||
		!strings.HasSuffix(filePath, ".go") {
		return nil, nil
	}

	ensureTypeIndex() // Ensure typeIndex is initialized

	// Canonicalize to the module-relative form used as the type-index key, so
	// lookups succeed regardless of whether the binary was built with -trimpath.
	normalizedFilePath = toModuleRelativePath(normalizedFilePath)

	// Look up the AST in TypeIndex using normalized paths
	astFile := typeIndex.LookupFile(normalizedFilePath)

	// If no AST file found in TypeIndex, attempt to parse it manually.
	// This ensures that tests using local filenames or temporary files still work.
	if astFile == nil {
		// Convert back to a filesystem path so the file can actually be opened.
		parsePath := fromModuleRelativePath(normalizedFilePath)
		slog.Debug("[openapi] ParseAnnotations: file not found in TypeIndex, attempting manual parse", "filePath", parsePath)
		fset := token.NewFileSet()
		var err error
		// Parse only comments as we only need those for annotations
		astFile, err = parser.ParseFile(fset, parsePath, nil, parser.ParseComments)
		if err != nil {
			slog.Warn("[openapi] ParseAnnotations: failed to parse file manually", "filePath", parsePath, "error", err)
			return nil, nil // Cannot proceed without AST
		}
	}

	// Update filePath and normalizedFilePath if we found a match via case-insensitive lookup
	// (though LookupFile doesn't return the path, we can assume it found it if astFile != nil and it was from index)
	normalizedFilePath = filepath.ToSlash(filePath)
	if strings.Contains(normalizedFilePath, "\\") {
		normalizedFilePath = strings.ReplaceAll(normalizedFilePath, "\\", "/")
	}

	// If a qualified function name was provided (e.g. "menu.handler_addons.List")
	// and the resolved file doesn't look like the intended one, try to find
	// a better match using the project's TypeIndex. This helps disambiguate
	// identical simple function names (like "List") that exist across
	// different packages/files (for example, menu and subscription both having
	// handler_addons.go with a List method).
	if strings.Contains(functionName, ".") && typeIndex != nil {
		slog.Debug(
			"[openapi] ParseAnnotations: starting TypeIndex disambiguation",
			"filePath",
			filePath,
			"functionName",
			functionName,
		)
		parts := strings.Split(functionName, ".")
		// We expect buildUniqueFunctionName to emit packageDir.fileName.funcName
		if len(parts) >= 3 {
			fileName := parts[len(parts)-2]
			packageDir := parts[len(parts)-3]
			// If current astFile/filePath does not already look like the qualified one,
			// search the TypeIndex for a matching file path and use its parsed AST.
			if astFile == nil ||
				(!strings.Contains(normalizedFilePath, "/"+fileName+".go") && !strings.Contains(normalizedFilePath, "/"+packageDir+"/")) {
				for p, f := range typeIndex.files {
					normalizedCandidate := filepath.ToSlash(p)
					if strings.HasSuffix(normalizedCandidate, "/"+fileName+".go") &&
						strings.Contains(normalizedCandidate, "/"+packageDir+"/") {
						astFile = f
						filePath = p
						normalizedFilePath = filepath.ToSlash(filePath)
						normalizedFilePath = normalizedCandidate
						slog.Debug(
							"[openapi] ParseAnnotations: selected AST from TypeIndex",
							"selected",
							p,
							"targetFileName",
							fileName,
							"packageDir",
							packageDir,
						)
						break
					}
				}
			}
		} else if len(parts) == 2 {
			// Possible formats: package.func or file.func - try to match by file or package
			cand := parts[0]
			if astFile == nil || (!strings.Contains(normalizedFilePath, "/"+cand+".go") && !strings.Contains(normalizedFilePath, "/"+cand+"/")) {
				for p, f := range typeIndex.files {
					normalizedCandidate := filepath.ToSlash(p)
					if strings.HasSuffix(normalizedCandidate, "/"+cand+".go") || strings.Contains(normalizedCandidate, "/"+cand+"/") {
						astFile = f
						filePath = p
						normalizedFilePath = filepath.ToSlash(filePath)
						normalizedFilePath = normalizedCandidate
						slog.Debug("[openapi] ParseAnnotations: selected AST from TypeIndex", "selected", p, "candidate", cand)
						break
					}
				}
			}
		}
	} else {
		slog.Debug("[openapi] ParseAnnotations: no TypeIndex disambiguation performed", "filePath", filePath, "functionName", functionName)
	}

	// Find the function and its comment
	var comment string

	// Extract actual function name from qualified name (e.g., "menu.List" -> "List")
	actualFunctionName := functionName
	if dotIndex := strings.LastIndex(functionName, "."); dotIndex != -1 {
		actualFunctionName = functionName[dotIndex+1:]
	}

	slog.Debug(
		"[openapi] ParseAnnotations: locating function comments",
		"filePath",
		filePath,
		"qualified",
		functionName,
		"actual",
		actualFunctionName,
	)

	for _, decl := range astFile.Decls {
		if funcDecl, ok := decl.(*ast.FuncDecl); ok {
			if funcDecl.Name.Name == actualFunctionName {
				if funcDecl.Doc != nil {
					comment = funcDecl.Doc.Text()
					slog.Debug(
						"[openapi] ParseAnnotations: comment block found",
						"file",
						filePath,
						"function",
						actualFunctionName,
					)
					break
				}
				// found function but no doc comments
				slog.Debug(
					"[openapi] ParseAnnotations: function found but missing comments",
					"file",
					filePath,
					"function",
					actualFunctionName,
				)
			}
		}
	}

	if comment == "" {
		slog.Debug(
			"[openapi] ParseAnnotations: no annotation comment found",
			"file",
			filePath,
			"function",
			actualFunctionName,
		)
		return nil, nil
	}

	annotation, err := parseAnnotationComment(comment)
	if err != nil {
		return nil, fmt.Errorf("[openapi] ParseAnnotations: %w", err)
	}

	return annotation, nil
}

// mergeAnnotations merges in middleware-then-handler order: slices are
// concatenated, scalars/pointers overwritten by the last non-empty value (so the
// handler wins). Returns nil only if every input is nil.
func mergeAnnotations(anns []*Annotation) *Annotation {
	var merged *Annotation
	for _, a := range anns {
		if a == nil {
			continue
		}
		if merged == nil {
			merged = &Annotation{}
		}

		if a.Summary != "" {
			merged.Summary = a.Summary
		}
		if a.Description != "" {
			merged.Description = a.Description
		}
		merged.Tags = append(merged.Tags, a.Tags...)
		merged.Accept = append(merged.Accept, a.Accept...)
		merged.Security = append(merged.Security, a.Security...)
		merged.Parameters = append(merged.Parameters, a.Parameters...)
		merged.Failures = append(merged.Failures, a.Failures...)

		if a.See != nil {
			merged.See = a.See
		}
		if a.Success != nil {
			merged.Success = a.Success
		}
	}
	return merged
}

// parseAnnotationComment decodes a doc-comment annotation block into an
// Annotation using the serde DSL decoder. A bare @Accept (with no value) is
// reported as an error by the decoder.
func parseAnnotationComment(comment string) (*Annotation, error) {
	annotation := &Annotation{}
	if err := serde.Unmarshal(comment, annotation); err != nil {
		return nil, err
	}

	return annotation, nil
}
