package openapi

import (
	"go/ast"
	"go/parser"
	"go/token"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"sort"
	"strings"
)

var (
	trailingIdentRegexp  = regexp.MustCompile(`([A-Za-z_][A-Za-z0-9_]*)$`)
	receiverMethodRegexp = regexp.MustCompile(`\(\*?([A-Za-z_][A-Za-z0-9_]*)\)\.([A-Za-z_][A-Za-z0-9_]*)$`)
	anonFuncRegexp       = regexp.MustCompile(`\.func\d+(?:\.\d+)*$`)
)

// HandlerInfo describes the source location for a handler function.
type HandlerInfo struct {
	File         string
	FunctionName string
	Package      string
}

// extractHandlerInfo resolves an http.Handler to source-level information.
func (g *Generator) extractHandlerInfo(handler http.Handler, route string) *HandlerInfo {
	slog.Debug("[openapi] extractHandlerInfo: called")

	handlerValue := reflect.ValueOf(handler)
	if handlerValue.Kind() != reflect.Func {
		slog.Warn(
			"[openapi] ignoring handler: only HandlerFunc-style handlers are supported "+
				"(a named function or a method on a receiver)",
			"kind", handlerValue.Kind().String(),
			"route", route,
		)
		return nil
	}

	pc := handlerValue.Pointer()

	if cached := g.getHandlerFromCache(pc); cached != nil {
		return cached
	}

	funcInfo := runtime.FuncForPC(pc)
	if funcInfo == nil {
		return nil
	}

	file, _ := funcInfo.FileLine(pc)
	rawName := funcInfo.Name()

	if anonFuncRegexp.MatchString(strings.TrimSuffix(rawName, "-fm")) {
		slog.Warn(
			"[openapi] ignoring handler: anonymous functions are not supported "+
				"(use a named function or a method on a receiver)",
			"rawName", rawName,
			"route", route,
		)
		return nil
	}

	name := resolveRuntimeName(rawName)

	slog.Debug(
		"[openapi] extractHandlerInfo: runtime info",
		"file", file,
		"rawName", rawName,
		"name", name,
		"route", route,
	)

	recvType, methodName, hasReceiver := extractReceiverAndMethod(rawName)

	if file == "<autogenerated>" || file == "" {
		if hasReceiver {
			if typeIndex != nil {
				if candPath, candMethod, found := findCandidatesInTypeIndex(typeIndex, recvType, methodName, route); found {
					file = candPath
					name = candMethod
					goto resolved
				}
			}

			if projectRoot := findProjectRoot(); projectRoot != "" {
				if path := scanProjectForMethod(projectRoot, recvType, methodName); path != "" {
					file = path
					name = methodName
					goto resolved
				}
			}
		}
	}

resolved:
	unique := buildUniqueFunctionName(file, name)
	slog.Debug("[openapi] extractHandlerInfo: resolved", "file", file, "unique", unique)

	if file != "" {
		if alt := preferRouteSegmentCandidate(typeIndex, route, file, recvType, name); alt != "" {
			slog.Debug(
				"[openapi] extractHandlerInfo: preferRouteSegmentCandidate switched file",
				"from", file,
				"to", alt,
				"route", route,
			)
			file = alt
			unique = buildUniqueFunctionName(file, name)
		}
	}

	if name == "" || unique == "" {
		slog.Warn(
			"[openapi] ignoring handler: unable to resolve a function name",
			"rawName", rawName,
			"route", route,
		)
		return nil
	}

	hi := &HandlerInfo{File: file, FunctionName: unique}
	g.setHandlerCache(pc, hi)
	return hi
}

// getHandlerFromCache looks up handler info for a function pointer.
func (g *Generator) getHandlerFromCache(pc uintptr) *HandlerInfo {
	g.cacheMu.RLock()
	defer g.cacheMu.RUnlock()
	return g.handlerCache[pc]
}

// setHandlerCache stores handler info for a function pointer.
func (g *Generator) setHandlerCache(pc uintptr, hi *HandlerInfo) {
	g.cacheMu.Lock()
	g.handlerCache[pc] = hi
	g.cacheMu.Unlock()
}

// resolveRuntimeName extracts a short function/method name from a runtime symbol.
func resolveRuntimeName(raw string) string {
	name := strings.TrimSuffix(raw, "-fm")
	if m := trailingIdentRegexp.FindString(name); m != "" {
		return m
	}
	return name
}

// extractReceiverAndMethod parses the receiver type and method from a runtime name.
func extractReceiverAndMethod(raw string) (recvType, method string, ok bool) {
	rawClean := strings.TrimSuffix(raw, "-fm")
	if m := receiverMethodRegexp.FindStringSubmatch(rawClean); len(m) == 3 {
		return m[1], m[2], true
	}
	return "", "", false
}

// handlerCandidate is a handler method declaration found in the type index.
type handlerCandidate struct {
	path    string
	method  string
	pkgName string
}

// findCandidatesInTypeIndex locates handler methods in the type index.
func findCandidatesInTypeIndex(ti *TypeIndex, recvType, methodName, route string) (path, method string, found bool) {
	var candidates []handlerCandidate

	for path, af := range ti.files {
		pkgName := ""
		if af.Name != nil {
			pkgName = af.Name.Name
		}
		for _, decl := range af.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Name == nil || fd.Name.Name != methodName {
				continue
			}
			if len(fd.Recv.List) == 0 {
				continue
			}

			switch recv := fd.Recv.List[0].Type.(type) {
			case *ast.StarExpr:
				if ident, ok := recv.X.(*ast.Ident); ok && ident.Name == recvType && fd.Doc != nil {
					candidates = append(candidates, handlerCandidate{path: path, method: methodName, pkgName: pkgName})
				}
			case *ast.Ident:
				if recv.Name == recvType && fd.Doc != nil {
					candidates = append(candidates, handlerCandidate{path: path, method: methodName, pkgName: pkgName})
				}
			}
		}
	}

	if best := disambiguateCandidates(candidates, recvType, methodName, route); best != nil {
		return best.path, best.method, true
	}
	return "", "", false
}

// disambiguateCandidates picks the single candidate that best matches the route,
// returning nil when there are no candidates or the choice is ambiguous. The
// winner is the candidate whose receiver type, method name, file path segments
// and package name match the most route segments; a tie (or no matches at all)
// is treated as ambiguous and logged.
func disambiguateCandidates(candidates []handlerCandidate, recvType, methodName, route string) *handlerCandidate {
	if len(candidates) == 0 {
		return nil
	}
	if len(candidates) == 1 {
		return &candidates[0]
	}

	sort.Slice(candidates, func(i, j int) bool { return candidates[i].path < candidates[j].path })

	segments := routeMatchSegments(route)

	bestScore := -1
	bestIdx := -1
	tie := false
	for i, c := range candidates {
		identifiers := append([]string{recvType, c.method}, pathSegments(c.path)...)

		if c.pkgName != "" && !strings.EqualFold(c.pkgName, filepath.Base(filepath.Dir(c.path))) {
			identifiers = append(identifiers, c.pkgName)
		}
		score := scoreRouteSegments(segments, identifiers...)
		switch {
		case score > bestScore:
			bestScore, bestIdx, tie = score, i, false
		case score == bestScore:
			tie = true
		}
	}

	if bestScore <= 0 || tie {
		paths := make([]string, len(candidates))
		for i, c := range candidates {
			paths[i] = c.path
		}
		slog.Warn(
			"[openapi] ignoring handler: ambiguous receiver+method, unable to pick a single file",
			"receiver", recvType,
			"method", methodName,
			"route", route,
			"candidates", paths,
		)
		return nil
	}

	return &candidates[bestIdx]
}

// routeMatchSegments returns the route path segments used for disambiguation,
// excluding empty segments, path parameters ({...}) and catch-all (*).
func routeMatchSegments(route string) []string {
	var segments []string
	for seg := range strings.SplitSeq(route, "/") {
		if seg == "" || strings.ContainsAny(seg, "{}*") {
			continue
		}
		segments = append(segments, seg)
	}
	return segments
}

// pathSegments returns the directory segments and the file-name stem of a file
// path, used as additional identifiers for route disambiguation (e.g. a handler
// in ".../billing/invoices/handler.go" yields "billing", "invoices", "handler").
func pathSegments(path string) []string {
	var segments []string
	for seg := range strings.SplitSeq(filepath.ToSlash(path), "/") {
		if seg == "" {
			continue
		}
		segments = append(segments, strings.TrimSuffix(seg, ".go"))
	}
	return segments
}

// scoreRouteSegments counts how many route segments match any of the given
// identifiers (package name, receiver type, method name, and the file's
// directory path segments). Matching is case-insensitive and bidirectional
// substring, so "users" matches both a "user" package and a "ListUsers" method.
func scoreRouteSegments(segments []string, identifiers ...string) int {
	lowered := make([]string, 0, len(identifiers))
	for _, id := range identifiers {
		if id != "" {
			lowered = append(lowered, strings.ToLower(id))
		}
	}

	count := 0
	for _, seg := range segments {
		s := strings.ToLower(seg)
		for _, id := range lowered {
			if strings.Contains(id, s) || strings.Contains(s, id) {
				count++
				break
			}
		}
	}
	return count
}

// scanProjectForMethod walks the project and returns the first file that matches receiver+method.
func scanProjectForMethod(projectRoot, recvType, methodName string) string {
	fset := token.NewFileSet()
	var foundPath string

	_ = filepath.Walk(projectRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}

		parsed, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}

		for _, decl := range parsed.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Name == nil || fd.Name.Name != methodName {
				continue
			}

			if len(fd.Recv.List) == 0 {
				continue
			}

			switch recv := fd.Recv.List[0].Type.(type) {
			case *ast.StarExpr:
				if ident, ok := recv.X.(*ast.Ident); ok && ident.Name == recvType && fd.Doc != nil {
					foundPath = path
					return filepath.SkipDir
				}
			case *ast.Ident:
				if recv.Name == recvType && fd.Doc != nil {
					foundPath = path
					return filepath.SkipDir
				}
			}
		}

		return nil
	})

	return foundPath
}

// buildUniqueFunctionName composes a deterministic function identifier.
func buildUniqueFunctionName(file, name string) string {
	if file == "" || file == "<autogenerated>" {
		return name
	}

	normalized := filepath.ToSlash(file)
	parts := strings.Split(normalized, "/")

	var fileName string
	if len(parts) > 0 {
		fileName = strings.TrimSuffix(parts[len(parts)-1], ".go")
	}

	var packageDir string
	for i := len(parts) - 1; i >= 0; i-- {
		if parts[i] != "" && !strings.HasSuffix(parts[i], ".go") {
			packageDir = parts[i]
			break
		}
	}

	switch {
	case packageDir != "" && fileName != "":
		return packageDir + "." + fileName + "." + name
	case packageDir != "":
		return packageDir + "." + name
	default:
		return name
	}
}

// preferRouteSegmentCandidate prefers files whose path matches the route segment.
// recvType is the receiver type name for a method, or "" for a top-level function;
// only declarations with a matching receiver (or no receiver) are considered, so a
// mere method-name collision cannot override a correctly resolved file.
func preferRouteSegmentCandidate(ti *TypeIndex, route, currentFile, recvType, methodName string) string {
	if ti == nil {
		return ""
	}

	segments := strings.Split(route, "/")
	var routeSeg string
	for i := len(segments) - 1; i >= 0; i-- {
		seg := segments[i]
		if strings.ContainsAny(seg, "{}*") {
			continue
		}
		routeSeg = seg
		break
	}

	normalizedCurrent := filepath.ToSlash(currentFile)
	if routeSeg == "" || strings.Contains(normalizedCurrent, "/"+routeSeg+"/") {
		return ""
	}

	for path, af := range ti.files {
		normalizedPath := filepath.ToSlash(path)
		if !strings.Contains(normalizedPath, "/"+routeSeg+"/") {
			continue
		}
		for _, decl := range af.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Name == nil || fd.Name.Name != methodName {
				continue
			}
			if receiverMatches(fd, recvType) {
				return path
			}
		}
	}

	return ""
}

// receiverMatches reports whether fd's receiver matches recvType. When recvType is
// empty, it matches only top-level functions (no receiver).
func receiverMatches(fd *ast.FuncDecl, recvType string) bool {
	if recvType == "" {
		return fd.Recv == nil
	}
	if fd.Recv == nil || len(fd.Recv.List) == 0 {
		return false
	}
	switch recv := fd.Recv.List[0].Type.(type) {
	case *ast.StarExpr:
		ident, ok := recv.X.(*ast.Ident)
		return ok && ident.Name == recvType
	case *ast.Ident:
		return recv.Name == recvType
	}
	return false
}
